# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoFase', models.IntegerField()),
                ('codigoNivel', models.IntegerField()),
                ('codSnip', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fechReg', models.DateField(max_length=40)),
                ('costoPip', models.FloatField()),
                ('costoDir', models.FloatField()),
                ('codFuncion', models.CharField(max_length=100)),
                ('codDepartament', models.IntegerField()),
                ('codProvincia', models.IntegerField()),
                ('codDiestrito', models.IntegerField()),
                ('codCli', models.IntegerField()),
                ('codEsp', models.IntegerField()),
                ('codResp', models.IntegerField()),
                ('observacion', models.CharField(max_length=500)),
                ('vigente', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCosto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoNivel', models.IntegerField()),
                ('costoDir', models.FloatField()),
                ('costoEquipo', models.FloatField()),
                ('costoAdm', models.FloatField()),
                ('costoImp', models.FloatField()),
                ('costoOtros', models.FloatField()),
                ('observacion', models.CharField(max_length=500)),
                ('costoPIP', models.FloatField()),
                ('vigente', models.CharField(max_length=1)),
                ('codFase', models.IntegerField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoFase', models.IntegerField()),
                ('codigoNivel', models.IntegerField()),
                ('fechInicio', models.DateField(max_length=40)),
                ('fechFin', models.DateField(max_length=40)),
                ('costEst', models.FloatField()),
                ('codDoc', models.IntegerField()),
                ('observacion', models.CharField(max_length=500)),
                ('estPyto', models.IntegerField()),
                ('tipoEntregable', models.IntegerField()),
                ('codEntrega', models.IntegerField()),
                ('codEsp', models.IntegerField()),
                ('codResp', models.IntegerField()),
                ('vigente', models.CharField(max_length=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('horror', 'Horror'), ('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')], max_length=10)),
            ],
        ),
    ]
