# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fechReg',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyectodocs',
            name='fechFin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyectodocs',
            name='fechInicio',
            field=models.DateField(),
        ),
    ]
