# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20171018_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='vigente',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='proyectocosto',
            name='vigente',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='proyectodocs',
            name='vigente',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
