# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20171018_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectodocs',
            name='codDoc',
        ),
    ]
